name: Generate docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/CHANGELOG.MD'
      - 'api/v1beta1/*types.go'
      - 'api/v1beta1/additional.go'
      - 'api/victoriametrics/v1beta1/*types.go'
      - 'api/victoriametrics/v1beta1/additional.go'
      - 'internal/config/config.go'

jobs:
  push-docs:
    runs-on: ubuntu-latest
    environment:
      name: docs
      url: https://docs.victoriametrics.com/
    steps:
      -
        name: Check out operator code
        uses: actions/checkout@v3
        with:
          repository: Amper/operator
          ref: master
          token: ${{ secrets.VM_BOT_GH_TOKEN }}
          path: "__vm-operator-repo"
      -
        name: Check out VM code
        uses: actions/checkout@v3
        with:
          repository: Amper/VictoriaMetrics
          ref: master
          token: ${{ secrets.VM_BOT_GH_TOKEN }}
          path: "__vm-docs-repo"
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.VM_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.VM_BOT_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: "__vm-docs-repo"
      -
        name: Generate vars and api doc
        run: |
          make operator-conf
          make doc
        working-directory: "__vm-operator-repo"
      -
        name: Update CHANGELOG in VM docs
        run: |
          cat ./docs/CHANGELOG.MD > ../__vm-docs-repo/docs/operator/CHANGELOG.md
          cat ./vars.MD > ../__vm-docs-repo/docs/operator/vars.md
          cat ./doc_api.MD > ../__vm-docs-repo/docs/operator/api.md
        working-directory: "__vm-operator-repo"
      -
        name: Commit and push changes
        run: |
          git add docs/operator/CHANGELOG.md
          git add docs/operator/vars.md
          git add docs/operator/api.md
          git commit -S -m "Automatic update operator CHANGELOG"
          git push
        working-directory: "__vm-docs-repo"
